# (bg, fb)の組み合わせは▲が良い感じに隠れるように互いの色を指定してる
format = """
[](#10998c)\
$os\
$custom\
[](bg:#481099 fg:#10998c)\
$directory\
[](fg:#481099 bg:#99101d)\
$git_branch\
$git_status\
[](fg:#99101d bg:#619910)\
$golang\
$nodejs\
[](fg:#619910 bg:#1c222d)\
\n[❯](fg:#619910 bg:#1c222d) \
"""
# 右側に時刻を表示
# right_format="""
# [](#10998c)\
# $time\
# [](#10998c)
# """


# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#10998c"
style_root = "bg:#10998c"
format = '[ ](bg:#10998c fg:#DDED25)[$user ]($style)'
disabled = false

[directory]
style = "bg:#481099"
format = "[ $path ]($style)"
truncation_length = 3
# truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#99101d"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#99101d"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#619910"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#619910"
format = '[ $symbol ($version) ]($style)'

# 時刻の表示設定
[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#10998c"
# format = '[ [󰀀 󰀂 󰀃 󰀄](bold italic) $time [󰀂](bold italic)]($style)'
format = '[ $time]($style)'

# リポジトリの作者を表示
[custom.author]
command = 'git remote get-url origin | cut -d/ -f4'
detect_folders=['.git']
style = "bg:#10998c"
format = '[  ](bg:#10998c fg:#ffffff)[$output ]($style)'
